/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author profesor
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        iniciarModelos();
    }
    
    public Inicio(String usuario) {
        initComponents();
        jLabelSaludo.setText("Hola " + usuario);
        iniciarModelos();
    }

    
    private void iniciarModelos(){
        modeloBebidas = new DefaultComboBoxModel();
        modeloPizzas = new DefaultComboBoxModel();
        modeloBebidas.addElement("Colacola");
        modeloBebidas.addElement("Agua");
        modeloBebidas.addElement("Nestea");
        modeloPizzas.addElement("Carbonara");
        modeloPizzas.addElement("4 quesos");
        modeloPizzas.addElement("Barbacoa");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSaludo = new javax.swing.JLabel();
        jComboBoxMasas = new javax.swing.JComboBox<>();
        jComboBoxIngredientes = new javax.swing.JComboBox<>();
        jButtonEncargar = new javax.swing.JButton();
        jLabelEncargos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelSaludo.setText("Hola usuario");

        jComboBoxMasas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Producto:", "Bebida", "Pizza" }));
        jComboBoxMasas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxMasasMouseClicked(evt);
            }
        });
        jComboBoxMasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMasasActionPerformed(evt);
            }
        });

        jComboBoxIngredientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingredientes:", "Tomate", "Nata", "Oregano", "Queso" }));

        jButtonEncargar.setText("Encargar");
        jButtonEncargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEncargarMouseClicked(evt);
            }
        });

        jLabelEncargos.setText("Encargos");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxMasas, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonEncargar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxIngredientes, javax.swing.GroupLayout.Alignment.LEADING, 0, 132, Short.MAX_VALUE))
                    .addComponent(jLabelSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEncargos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jLabelEncargos)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jComboBoxMasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jComboBoxIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEncargar)))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEncargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEncargarMouseClicked
        String masa, ingrediente;
        
        masa = (String) jComboBoxMasas.getSelectedItem();
        ingrediente = (String) jComboBoxIngredientes.getSelectedItem();
        
        jTextArea1.setText(jTextArea1.getText() + "\n" + masa + " " + ingrediente);
        
    }//GEN-LAST:event_jButtonEncargarMouseClicked

    private void jComboBoxMasasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxMasasMouseClicked
       
        
        
    }//GEN-LAST:event_jComboBoxMasasMouseClicked

    private void jComboBoxMasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMasasActionPerformed
        int opc = jComboBoxMasas.getSelectedIndex();
        
        switch (opc){
            case 0:
                JOptionPane.showMessageDialog(rootPane, "Seleccione un producto","",2);
                break;
            case 1:
                jComboBoxIngredientes.setModel(modeloBebidas);
                break;
            case 2:
                jComboBoxIngredientes.setModel(modeloPizzas);
                break;
        }
    }//GEN-LAST:event_jComboBoxMasasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio("Juan").setVisible(true);
            }
        });
    }

    private javax.swing.DefaultComboBoxModel<String> modeloBebidas;
    private javax.swing.DefaultComboBoxModel<String> modeloPizzas;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEncargar;
    private javax.swing.JComboBox<String> jComboBoxIngredientes;
    private javax.swing.JComboBox<String> jComboBoxMasas;
    private javax.swing.JLabel jLabelEncargos;
    private javax.swing.JLabel jLabelSaludo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
